### PR TITLE
add a keyword denylist to prevent spam in flag requests

### PR DESCRIPTION
**Pull request by alucryd**
Here is a proposal for a flag requests blacklist as discussed

### CODE REVIEW

**Comment by jelly** [comment]
Tested works nicely, I would suggest renaming blacklist to denylist and then it's ready to merge!

**Comment by alucryd** [comment]
Done!

**Comment by alucryd** [comment]
Sorry, forgot 2 mentions of blacklist, just changed them.

**Review by jelly — APPROVED** [review]

**Comment by jelly** [comment]
Thanks!

**Pull request merged**
