### PR TITLE
dev dashboard: highlight table rows on mouse hover

### PR DESCRIPTION
**Pull request by eworm-de**
Signed-off-by: Christian Hesse <mail@eworm.de>

### CODE REVIEW

**Comment by foutrelis** [comment]
I guess this is what you were going for:

> < Bluewind> just tested this in the debugger and it works: #dev-dashboard tr:hover, #stats-area tr:hover

Seems best to revert this at the moment; please do submit a new corrected PR.

**Comment by eworm-de** [comment]
Uh, sorry.
Created my pull request from an old patch from my mailbox. Looks like anything changed since then...

This was supposed to highlight the row pointed by the mouse, just like in signoff list.

**Comment by eworm-de** [comment]
Mhh, it works for the stats area... I will looks into this.

**Comment by eworm-de** [comment]
Fixed in #41

**Pull request merged**
