### PR TITLE
Allow to download sig from "download from mirror"

### LINKED ISSUE #356: Make the signature available for "download from mirror"
The redirect logic for https://archlinux.org/packages/core/x86_64/filesystem/download/ does not follow signatures for download, as of now this is no issue  but in the future pacman might change this behaviour.

Change https://archlinux.org/packages/core/x86_64/filesystem/download/  to https://archlinux.org/packages/core/x86_64/filesystem/download

And allow redirection for https://archlinux.org/packages/core/x86_64/filesystem/download.sig

### PR DESCRIPTION
**Pull request by just1602**
Hello !

To fix this, I added a new url pattern that match `download.sig` and call the same `download` function with a new `sig` param to True.

It's been a while since the last time I did some django, so let me know if you'd like to see this fixed another way!

Fixes #356

### CODE REVIEW

**Review by jelly — CHANGES_REQUESTED** [review]
This does not really resolve the issue described in the ticket. The issue is that in the future pacman will append  ".sig" to the download url before redirect and as /download/.sig does not match this won't resolve the issue.

So we should rework the generated url to trim the trailing / and the same goes for the new download.sig url

**Comment by just1602** [comment]
Maybe there's something I don't get, but currently, on my machine when I `curl -L localhost:8000/packages/core/x86_64/filesystem/download --output test` I get the archive of the filesystem package.

When I `curl -L localhost:8000/packages/core/x86_64/filesystem/download.sig` I get the sig file of the filesystem package.

Is this not what you want, what can I change to make it works as desired?

**Comment by jelly** [comment]
> Maybe there's something I don't get, but currently, on my machine when I `curl -L localhost:8000/packages/core/x86_64/filesystem/download --output test` I get the archive of the filesystem package.
> 
> When I `curl -L localhost:8000/packages/core/x86_64/filesystem/download.sig` I get the sig file of the filesystem package.
> 
> Is this not what you want, what can I change to make it works as desired?

I see, but the packages page has download/, so fixed with:

```
-                <li><a href="download/" rel="nofollow" title="Download {{ pkg.pkgname }} from mirror">Download From Mirror</a>
+                <li><a href="download" rel="nofollow" title="Download {{ pkg.pkgname }} from mirror">Download From Mirror</a>>
```

**Comment by jelly** [comment]
merged via cf628634bb2226a277df8ae32694f4777cabad47

**Pull request closed without merging**
