### PR TITLE
extended release model to include wkd_email

### PR DESCRIPTION
**Pull request by fish-dango**
Extended the release model to include wdk_email. This is an addition proposed by #340. Please tell me if there anything else I can add or change!

### CODE REVIEW

**Comment by Foxboron** [comment]
This is missing the addition on the download page though. Shouldn't that be added in this pull-request?

**Comment by jelly** [comment]
> This is missing the addition on the download page though. Shouldn't that be added in this pull-request?

Yes, otherwise I'll have to do that

**Comment by fish-dango** [comment]
Sorry for the late response on my end! 

I misread the issue. I will add that right now!

**Comment by fish-dango** [comment]
I added the `gpg --auto-key-locate clear,wkd -v --locate-external-key {release.wkd_email}` to the Download template. Just encase I wanted to see here if I interpreted the request correctly here before I make another commit. Thank you! 

image

**Comment by Foxboron** [comment]
If you put it below `PGP Fingerprint` it would make more sense, but yes. That is what I was after! Thanks :)

**Comment by jelly** [comment]
> I added the `gpg --auto-key-locate clear,wkd -v --locate-external-key {release.wkd_email}` to the Download template. Just encase I wanted to see here if I interpreted the request correctly here before I make another commit. Thank you!
> 
> image

did you forget to push your changes, I don't see the edited download template yet in your pull request.

**Comment by fish-dango** [comment]
I just pushed my commits now! I had a bit of a hiccup with my own local copy of Archweb, but my changes should be in now!

**Comment by jelly** [comment]
Merged via 68b734e81728fef83a7ed0b5ec18af2931e2f3c8

**Pull request closed without merging**
