### PR TITLE
Add author to planet feed

### PR DESCRIPTION
**Pull request by gregoiredx**
Add author name to planet feed (as suggested by https://github.com/archlinux/archweb/issues/377).

### CODE REVIEW

**Comment by jelly** [comment]
Please have a look at the test failure

**Comment by gregoiredx** [comment]
OK, the tests needed a `DATABASES` settings. Easiest way to allow that is to use the `local_settings.py.example` as the `local_settings.py` used by the CI, WDYT?

**Comment by jelly** [comment]
> OK, the test needed a `DATABASES` settings. Easiest way to allow that is to use the `local_settings.py.example` as the `local_settings.py` used by the CI, WDYT? See [7d742a9](https://github.com/archlinux/archweb/commit/7d742a9c2b033f06c2f410b7b26921e8f9ba0d0d)

That can't be correct, it should never be required.

**Comment by gregoiredx** [comment]
@jelly, thanks for your review. 
You're right, the failing test had nothing to do with the `DATABASES` setting.
What made the test suite pass when using a  `local_settings.py` in the CI was the `CACHES` config: https://github.com/archlinux/archweb/blob/099162395c01dc2df9289be1d9dd7a500becf4fe/local_settings.py.example#L34-L40

Because there is a response cache on `/feeds/planet/`: https://github.com/archlinux/archweb/blob/d108095aac9c6203e9e1a8bcbfe0e59624f64bf8/urls.py#L69
So the test `test_feed_item()` was working well when run alone but was getting an empty items list if called after another test already calling  `/feeds/planet/` in a context where no `FeedItem` existed.

So I introduced a dummy cache config in the `conftest.py`, exactly like proposed in [pytest-django documentation](https://pytest-django.readthedocs.io/en/latest/configuring_django.html#overriding-individual-settings).

I think it makes sense to deactivate caching in test settings to avoid side effects between tests, WDYT?

**Comment by jelly** [comment]
> @jelly, thanks for your review. You're right, the failing test had nothing to do with the `DATABASES` setting. What made the test suite pass when using a `local_settings.py` in the CI was the `DummyCache` `CACHES` config:
> 
> https://github.com/archlinux/archweb/blob/099162395c01dc2df9289be1d9dd7a500becf4fe/local_settings.py.example#L34-L40
> 
> Because there is a response cache on `/feeds/planet/`:
> 
> https://github.com/archlinux/archweb/blob/d108095aac9c6203e9e1a8bcbfe0e59624f64bf8/urls.py#L69
> 
> 
> So the test `test_feed_item()` was working well when run alone but was getting an empty items list if called after another test already calling `/feeds/planet/` in a context where no `FeedItem` existed.
> So I introduced a dummy cache config in the `conftest.py`, exactly like proposed in [pytest-django documentation](https://pytest-django.readthedocs.io/en/latest/configuring_django.html#overriding-individual-settings).
> 
> I think it makes sense to deactivate caching in test settings to avoid side effects between tests, WDYT?

Nice catch, this rings a bell and I recall other tests do something with disabling / enabling the cache as well. I'll have a look over the weekend.

**Comment by gregoiredx** [comment]
Yep, the following code could probably be removed if we apply the global test fixture in this PR:
https://github.com/archlinux/archweb/blob/cc799ff11127a9c665c83f5896bde42dc98287cb/mirrors/tests/test_mirrorstatus.py#L13
https://github.com/archlinux/archweb/blob/cc799ff11127a9c665c83f5896bde42dc98287cb/mirrors/tests/test_mirrorstatus.py#L43

**Review by jelly — APPROVED** [review]

**Comment by jelly** [comment]
Thanks!

**Pull request merged**
