### PR TITLE
Change navbar image to font

### PR DESCRIPTION
**Pull request by syui**
This will replace the image of Navarbar with font.

### Why?

The image becomes coarse at a terminal with high resolution. Also, the display speed of the high resolution image is delayed.

We adopted Web Font to solve this problem.

### Advantage

- It will be easy to adjust the size, There is no need to edit images. CSS

- Event customization is easy

For example, let's light the logo.

```css
h1 a:hover span.icon-archlinux {
	-webkit-transition: 0.3s ease-in-out;
	-moz-transition: 0.3s ease-in-out;
	-o-transition: 0.3s ease-in-out;
	transition: 0.3s ease-in-out;
	-moz-text-shadow:0px 0px 1px black, 0 0 15px #38b7ea;
	-webkit-text-shadow:0px 0px 1px black, 0 0 15px #38b7ea;
	-o-text-shadow:0px 0px 1px black, 0 0 15px #38b7ea;
	text-shadow:0px 0px 1px black, 0 0 15px #38b7ea;
	color:#38b7ea;
}
```

Thank you for reading this to the end.

### CODE REVIEW

**Comment by Bluewind** [comment]
This changes the font in the logo. I'd much prefer using an svg version of the logo.

**Comment by Bluewind** [comment]
That's much better. Could you remove all the custom font stuff that is now not necessary any more from the PR?

Also I see you removed the small "TM" notice in the logo. Could you put it back in?

**Comment by syui** [comment]
Added svg image.

## Examples of using Web Font

> templates/base.html

```html
    	<div id="archnavbarlogo">
           <h1><a href="/" title="Return to the main page">
	        <span class="icon-archlinux"></span>
	        <span class="site-title-arch">arch</span>
	        <span class="site-title-linux">linux</span>
	    </a></h1>
        </div>
```

> sitestatic/archweb.css

```css
#archnavbarlogo a:link {
    text-decoration: none !important;
+  /* color: rgba(0, 0, 0, 0); */
}
```

## Examples of using images(SVG)

> templates/base.html

```html
	    <div id="archnavbarlogo">
		<h1><a href="/" title="Return to the main page">
	    		Arch Linux
	    	</a></h1>
            </div>
```

**Comment by syui** [comment]
Yes, I think you can delete custom fonts and add TM.

**Comment by syui** [comment]
done

**Comment by Bluewind** [comment]
The svg you add contains an inlined png image rather than vector graphics. You can find a full svg version of our logo [here](https://www.archlinux.org/art/). You just have to increase the size of the text relative to the icon to match the old one.

Apart from this, the changes are fine. Could you squash them into a single commit?

**Comment by syui** [comment]
done

**Comment by syui** [comment]
@Bluewind The adjustment is completed.

Thank you for reading this to the end.

**Comment by Bluewind** [comment]
Great!

Ready for merge from my side. @angvp, @grazzolini?

**Comment by grazzolini** [comment]
I'm ok with it too. If @angvp merges it, I can run the book.

**Comment by angvp** [comment]
@Bluewind @grazzolini will try it tomorrow and do the merge if it seems ok, will send an e-mail to Gian Carlo to run the playbook.

**Pull request merged**
