### PR TITLE
[RFC] Upgrade django

### PR DESCRIPTION
**Pull request by jelly**
@grazzolini maybe check this too? 👍

### CODE REVIEW

**Comment by jelly** [comment]
I think the commits might need some re-ordering.

**Comment by angvp** [comment]
@jelly After merging the TravisCI commit this PR might be need updated in order to trigger TravisCI to start running the tests

**Comment by jelly** [comment]
@angvp no problem, I'm not in a rush yet to merge this :) Will happily rebase it on master later.

**Comment by jelly** [comment]
Two warnings left:
```
WARNINGS:
releng.Test.modules: (fields.W340) null has no effect on ManyToManyField.
releng.Test.rollback_modules: (fields.W340) null has no effect on ManyToManyField.
```

**Comment by jelly** [comment]
Updated to 1.8.17

**Comment by angvp** [comment]
Rebase to master again and let's see if it pick travisCI :)

**Comment by jelly** [comment]
@angvp Rebased and tests pass somehow 👍

**Comment by angvp** [comment]
@grazzolini I'm ok to merge this, let's schedule a date for doing this deploy and run a rollback if something gets wrong?

**Comment by grazzolini** [comment]
@angvp @jelly
I have been following this, I did my own tests a month ago on this branch. I didn't test the newer commits, but I didn't saw anything that troublesome. I think we can do this: Stop services, stop archweb. Stop anything that might write to the db. Do a DB backup and a backup of the directories. Then we deploy this branch and test service by service and view by view on production. I estimate we'll take a couple of hours to do this, would be better if all the three of us could do it together. I'm somewhat used with these big deployments.

**Pull request merged**
