### PR TITLE
Some py3 fixes and some refactoring

### PR DESCRIPTION
**Pull request by akstrfn**

### CODE REVIEW

**Comment by akstrfn** [comment]
It's not a must but I'd also check the automatic list wrapping that 2to3
tool made before rolling py3. It should be a quick review. I made them
after reviewing your py3 PR.

Few commits do change the logic so better check them in details whenever
you can.

**Comment by akstrfn** [comment]
I managed to fix a few more problem related to py3 and django 2. But tests fail on my machine...

**Comment by jelly** [comment]
I've just merged python3 to master, if anything from this branch is still required please rebase.

**Comment by akstrfn** [comment]
I'll probably rebase this weekend.

**Comment by akstrfn** [comment]
Rebased and changed the merge target to master.

**Comment by jelly** [comment]
Awesome, the list() and mypy (although I don't really use it) commit looks good. I want to test the other code improvement for the new user page and then merge it :+1:

**Pull request merged**
