### PR TITLE
update support staff description

### PR DESCRIPTION
**Pull request by Foxboron**
This is the patch from https://bugs.archlinux.org/task/44626.

Made a pull-request for visibility

### CODE REVIEW

**Comment by jelly** [comment]
Seen it, I think I didn't like it.

**Comment by lahwaacz** [comment]
> Seen it, I think I didn't like it.

Please be specific about what you don't like about the patch. Blocking the issue for no reason is not going to get us anywhere.

**Comment by jelly** [comment]
Relax, this was a reminder for me to look into it....

**Comment by lahwaacz** [comment]
Or we can discuss in on the internal staff mailing list... (please read my today's message there)

**Comment by jelly** [comment]
We should get every staff member on the staff group on the actual page instead of linking to the separate pages. Note that links aren't accepted in the description of the staff group page.

**Comment by jelly** [comment]
Closed, due to no updates.

**Pull request closed without merging**
