### PR TITLE
PEP8 the codebase

### PR DESCRIPTION
**Pull request by just1602**
I had to create a PR since travis is failling to parse github response and let me signin, so until I fixed everything this is gonna be a draft PR.

### CODE REVIEW

**Comment by just1602** [comment]
I have the following errors, but in the file there is a comment that says this is to make the views available to other packages, so does I ignore this error, just mark them as `# noqa` or it's the comment is outdated and I can delete those lines? :)

```
packages/views/__init__.py:6:1: F401 'django.contrib.auth.models.User' imported but unused
packages/views/__init__.py:19:1: F401 '.display.details' imported but unused
packages/views/__init__.py:19:1: F401 '.display.groups' imported but unused     
packages/views/__init__.py:19:1: F401 '.display.group_details' imported but unused
packages/views/__init__.py:19:1: F401 '.display.files' imported but unused
packages/views/__init__.py:19:1: F401 '.display.details_json' imported but unused       
packages/views/__init__.py:19:1: F401 '.display.files_json' imported but unused
packages/views/__init__.py:19:1: F401 '.display.download' imported but unused
packages/views/__init__.py:21:1: F401 '.flag.flaghelp' imported but unused             
packages/views/__init__.py:21:1: F401 '.flag.flag' imported but unused                                                                            
packages/views/__init__.py:21:1: F401 '.flag.flag_confirmed' imported but unused       
packages/views/__init__.py:21:1: F401 '.flag.unflag' imported but unused                                                                          
packages/views/__init__.py:21:1: F401 '.flag.unflag_all' imported but unused           
packages/views/__init__.py:22:1: F401 '.search.search_json' imported but unused        
packages/views/__init__.py:23:1: F401 '.signoff.signoffs' imported but unused          
packages/views/__init__.py:23:1: F401 '.signoff.signoff_package' imported but unused   
packages/views/__init__.py:23:1: F401 '.signoff.signoff_options' imported but unused   
packages/views/__init__.py:23:1: F401 '.signoff.signoffs_json' imported but unused
```

**Comment by jelly** [comment]
> I have the following errors, but in the file there is a comment that says this is to make the views available to other packages, so does I ignore this error, just mark them as `# noqa` or it's the comment is outdated and I can delete those lines? :)
> 

Just checked and the comment is certainly true

```
[jelle@natrium][~/projects/archweb]%git grep group_details
packages/urls_groups.py:from packages.views import groups, group_details
packages/urls_groups.py:    url(r'^(?P<arch>[A-z0-9]+)/(?P<name>[^ /]+)/$', group_details),
packages/views/__init__.py:from .display import (details, groups, group_details, files, details_json,
packages/views/display.py:def group_details(request, arch, name):
```

Not sure if I'd like # noqa, might be better to fix the imports. Are these all unused imports?

> ```
> packages/views/__init__.py:6:1: F401 'django.contrib.auth.models.User' imported but unused
> packages/views/__init__.py:19:1: F401 '.display.details' imported but unused
> packages/views/__init__.py:19:1: F401 '.display.groups' imported but unused     
> packages/views/__init__.py:19:1: F401 '.display.group_details' imported but unused
> packages/views/__init__.py:19:1: F401 '.display.files' imported but unused
> packages/views/__init__.py:19:1: F401 '.display.details_json' imported but unused       
> packages/views/__init__.py:19:1: F401 '.display.files_json' imported but unused
> packages/views/__init__.py:19:1: F401 '.display.download' imported but unused
> packages/views/__init__.py:21:1: F401 '.flag.flaghelp' imported but unused             
> packages/views/__init__.py:21:1: F401 '.flag.flag' imported but unused                                                                            
> packages/views/__init__.py:21:1: F401 '.flag.flag_confirmed' imported but unused       
> packages/views/__init__.py:21:1: F401 '.flag.unflag' imported but unused                                                                          
> packages/views/__init__.py:21:1: F401 '.flag.unflag_all' imported but unused           
> packages/views/__init__.py:22:1: F401 '.search.search_json' imported but unused        
> packages/views/__init__.py:23:1: F401 '.signoff.signoffs' imported but unused          
> packages/views/__init__.py:23:1: F401 '.signoff.signoff_package' imported but unused   
> packages/views/__init__.py:23:1: F401 '.signoff.signoff_options' imported but unused   
> packages/views/__init__.py:23:1: F401 '.signoff.signoffs_json' imported but unused
> ```

**Comment by just1602** [comment]
Yeah, they're all unused in the file where they're import.

**Comment by jelly** [comment]
> Yeah, they're all unused in the file where they're import.

Yes, but check the snippet I posted, removing them is fine if you fix the imports in urls.py

**Comment by just1602** [comment]
@jelly this is a pretty long PR to review. Would you prefer I split the commit in django app, so it'd be easier to review? I'm pretty sure it's alright, but since the code coverage isn't that high, I wouldn't rely only on tests in the ci.. :/

**Comment by jelly** [comment]
> @jelly this is a pretty long PR to review. Would you prefer I split the commit in django app, so it'd be easier to review? I'm pretty sure it's alright, but since the code coverage isn't that high, I wouldn't rely only on tests in the ci.. :/

It looks pretty ok, but there are some nitpicks:

* I'd raise the max-line-length to 200 or 300, as 120 is too limiting
* I don't like reformatting/fixing migrations, these are autogenerated and shouldn't be linted at all

**Comment by just1602** [comment]
Alright @jelly I'll try to fix this asap!

**Comment by jelly** [comment]
Looks good, but it seems you didn't rebase properly? (I noticed a merge commit), also please revert the changes for the migrations.

You probably want to use 
```
git checkout master -- devel/migrations
```

**Review by jelly — APPROVED** [review]

**Pull request merged**
