### PR TITLE
Donate

### PR DESCRIPTION
**Pull request by grazzolini**
Sponsor cleanup

### CODE REVIEW

**Comment by jelly** [comment]
Test fails since the logo is still used in the "retro" pages. So either remove it there or re-add it.

**Comment by grazzolini** [comment]
Not just that, the logo is on the index page as well. I forgot to search for it. I need to remind myself to always run the tests before pushing.

**Comment by jelly** [comment]
You might wanna squash the commits into one commit 👍

**Comment by grazzolini** [comment]
Instead of squash, I marked both as fixup, so they don't appear on the log. It is as if they did not happen.

**Pull request merged**
