### PR TITLE
Add setup.cfg with pytest configuration

### PR DESCRIPTION
**Pull request by blueyed**
This allows for using pytest easily, after installing it (and
pytest-django).

TODO:
- [ ] update after/for https://github.com/archlinux/archweb/pull/48#issuecomment-312925869

### CODE REVIEW

**Comment by jelly** [comment]
Any reason to prefer pytest above nose?

**Comment by blueyed** [comment]
Currently it is just a wrapper, using the Django-compatible mode, but I would really like it to become the default test runner, so that its features (https://docs.pytest.org/en/latest/#id1) could be used.
I do not want to push for that, but this config allows for using it with the existing unittest/Django based tests already for now.

**Comment by angvp** [comment]
As long as I'd like to use pytest eventually I don't see yet this PR as it will be merged now, thanks anyway @blueyed I will let it open for later when refactoring some of the test architecture.

**Comment by jelly** [comment]
I've chosen to prefer a pytest.ini in https://github.com/jelly/archweb/commit/bda9a1d197ba70fa9d638a3ca195ece41dfe1516

**Pull request closed without merging**
