### PR TITLE
Set icon font

### PR DESCRIPTION
**Pull request by syui**
## Before

`Expansion:300%`

## After

`Expansion:300%`

## Link effect

`mouse-over`

## Icon font

[https://github.com/FortAwesome/Font-Awesome](https://github.com/FortAwesome/Font-Awesome)

[https://icomoon.io/](https://icomoon.io/)

### CODE REVIEW

**Comment by Alir3z4** [comment]
Very nice.
SVG is a must,

**Comment by syui** [comment]
Thx.

**Comment by Bluewind** [comment]
Why did you close this if it has not been merged and there is no feedback from the project maintainer?

**Comment by syui** [comment]
@Bluewind 
I had to organize the `pull request` lately.
And no feedback from the project maintainer.

**Pull request closed without merging**
